### ISSUE TITLE
How to install and user

### ISSUE THREAD

**Issue by balazsnemeth** [yamadapc/git-toggl#1]
Could you write some sentence in the readme.md about how to install and use this plugin?

**Comment by yamadapc** [comment]
Hey, this still needs work before it's really useful... You'd need Haskell to install. I wouldn't recommend using it unless you want to contribute.

Building would be something in these lines if you have `stack` installed:

```
$ git clone git@github.com:yamadapc/git-toggl
# ...
$ cd git-toggl
$ stack init && stack build
```
